name: Smartban
version: '1.0-SNAPSHOT'
main: org.viirless.smartban.BanPlugin
api-version: '1.21'

commands:
  ban:
    description: Ban a player with configurable reasons
    usage: /ban <player> <id>
    permission: banplugin.ban
  unban:
    description: Unban a player
    usage: /unban <player>
    permission: banplugin.unban
  kick:
    description: Kick a player with a custom reason
    usage: /kick <player> <reason>
    permission: banplugin.kick

permissions:
  banplugin.ban:
    description: Allows banning players
    default: false
  banplugin.unban:
    description: Allows unbanning players
    default: false
  banplugin.kick:
    description: Allows kicking players
    default: false
  banplugin.bypass:
    description: Prevents being banned by other staff members
    default: false
  banplugin.kick.bypass:
    description: Prevents being kicked by other staff members
    default: false
  banplugin.admin:
    description: Full ban plugin access
    default: false
    children:
      banplugin.ban: true
      banplugin.unban: true
      banplugin.kick: true
  banplugin.*:
    description: All ban plugin permissions
    default: false
    children:
      banplugin.admin: true
      banplugin.bypass: true
      banplugin.kick.bypass: true