name: Smartbans
version: 'BETA 1.4'
main: org.viirless.smartban.BanPlugin
api-version: '1.21'

commands:
  ban:
    description: Ban a player with configurable reasons
    usage: /ban <player> <id>
  unban:
    description: Unban a player
    usage: /unban <player>
  kick:
    description: Kick a player with a custom reason
    usage: /kick <player> <reason>
  mute:
    description: Mute a player with configurable reasons
    usage: /mute <player> <id>
  unmute:
    description: Unmute a player
    usage: /unmute <player>
  history:
    description: View a player's ban and mute history
    usage: /history <player>
  smartbans:
    description: Reload the plugin configuration
    usage: /smartbans reload

permissions:
  banplugin.ban:
    description: Allows banning players
    default: op
  banplugin.unban:
    description: Allows unbanning players
    default: op
  banplugin.kick:
    description: Allows kicking players
    default: op
  banplugin.mute:
    description: Allows muting players
    default: op
  banplugin.unmute:
    description: Allows unmuting players
    default: op
  banplugin.bypass:
    description: Prevents being banned, kicked or muted by other staff members
    default: op
  banplugin.history:
    description: Allows viewing ban and mute history of players
    default: op
  banplugin.reload:
    description: Allows reloading the plugin configuration
    default: op
  banplugin.admin:
    description: Grants all administrative permissions
    default: op
    children:
      banplugin.ban: true
      banplugin.unban: true
      banplugin.kick: true
      banplugin.mute: true
      banplugin.unmute: true
      banplugin.history: true
      banplugin.reload: true
  banplugin.*:
    description: Grants all plugin permissions including bypass
    default: op
    children:
      banplugin.admin: true
      banplugin.bypass: true
